### ISSUE TITLE
Maven 3.3.3 missing

### ISSUE THREAD

**Issue by ioreskovic** [marcelbirkner/docker-ci-tool-stack#43]
After getting everything up, I wanted to run the build for selenium2-maven-project.
However, the following error occured:  
  

> Started by user anonymous
> Building in workspace /var/jenkins_home/jobs/selenium2-maven-project/workspace
>  > git rev-parse --is-inside-work-tree # timeout=10
> Fetching changes from the remote Git repository
>  > git config remote.origin.url https://github.com/marcelbirkner/selenium2-maven-project # timeout=10
> Fetching upstream changes from https://github.com/marcelbirkner/selenium2-maven-project
>  > git --version # timeout=10
>  > git -c core.askpass=true fetch --tags --progress https://github.com/marcelbirkner/selenium2-maven-project +refs/heads/*:refs/remotes/origin/*
> Seen branch in repository origin/master
> Seen 1 remote branch
> Checking out Revision 4aadfe3492345cb007d7f0abd62749bfc8294a10 (origin/master)
>  > git config core.sparsecheckout # timeout=10
>  > git checkout -f 4aadfe3492345cb007d7f0abd62749bfc8294a10
>  > git rev-list 4aadfe3492345cb007d7f0abd62749bfc8294a10 # timeout=10
> Cleaning workspace
>  > git rev-parse --verify HEAD # timeout=10
> Resetting working tree
>  > git reset --hard # timeout=10
>  > git clean -fdx # timeout=10
> Invalid tool ID 3.3.3
> FATAL: Couldn’t find any executable in /var/jenkins_home/tools/hudson.tasks.Maven_MavenInstallation/Maven_3.3.3
> Build step 'Invoke top-level Maven targets' marked build as failure
> Recording test results
> ERROR: Step ‘Publish JUnit test result report’ failed: No test report files were found. Configuration error?
> Finished: FAILURE

Given my limited understanding, I'd assume Maven 3.3.3 is not installed. Is there something I missed?

**Comment by marcelbirkner** [comment]
Hi @ioreskovic 

you should find the Maven configuration in the global Jenkins configuration.

**Comment by yanhongwang** [comment]
Hello,

I meet the same problem with **3.3.3** version. 
And I also do the "automatically install" procedure like this page.
https://stackoverflow.com/questions/38822130/jenkins-needs-to-know-where-your-maven-is-installed

And in official website list **some other version**. I tried with those version. It still showed the same error.
"Invalid tool ID"
http://apache.mirror.digionline.de/maven/maven-3/

This guy met the same issue before **3 year ago**.
http://jenkins-ci.361315.n4.nabble.com/hudson-maven-MavenVersionCallable-call-throws-NullPointerException-td4682792.html

Or do I miss some **important step** in Jenkins?
Otherwise could only solved by manually ...

Hong
